### ISSUE TITLE
Create Smart Contract without 0x Protocol

### ISSUE THREAD

**Issue by oojr** [forkdelta/proposals#10]
0x requires Mist/Metamask which makes it hard to write bots I don't think it is the best idea for the future @freeatnet

**Comment by freeatnet** [comment]
Please add your feedback in #4.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/proposals/issues/6

A new smart contract is being developed: https://github.com/forkdelta/smart_contract

As @freeatnet stated, please add your feedback to #4 

Closing as this proposal was addressed in other issues.
