### ISSUE TITLE
How to cancel order over API

### ISSUE THREAD

**Issue by kungla** [forkdelta/proposals#13]
Docs do not mention how to cancel my open order over ForkDelta API. Is it possible?

https://github.com/forkdelta/backend-replacement/tree/master/docs/api

**Comment by freeatnet** [comment]
@kungla Orders require order creator update the blockchain state; so, they cannot be cancelled via the API. To cancel an order, send a transaction calling `cancelOrder` on the current trading contract ([see line 306](https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819#code)).
