### ISSUE TITLE
Change Default Pair From PPT-ETH To DAI-ETH

### ISSUE THREAD

**Issue by zaptrem** [forkdelta/proposals#2]
Change default pair and landing page from PPT-ETH to DAI-ETH. 

Rationale:

1. More neutral (no bias toward any specific speculative token)
2. More intuitive (users are used to seeing the Big Three tied to USD values)

**Comment by zaptrem** [comment]
Implemented in https://github.com/forkdelta/forkdelta.github.io/pull/39

**Comment by freeatnet** [comment]
Done.
